package com.andrei;

public class SecondTask {
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

    public static int calculate(int maxValue) {
        int currentNumber = 1;
        int previousNumber = 1;
        int result = 0;
        while (currentNumber < maxValue) {
            if (currentNumber % 2 == 0) {
                result += currentNumber;
            }
            currentNumber = previousNumber + currentNumber;
            previousNumber = currentNumber - previousNumber;

        }
        return result;
    }
}
